apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: readytodev/5team-front
  newName: readytodev/5team-front
  newTag: 27943f5ca6f9ace3d0b95592b52f9b0347684f1a
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
