apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: readytodev/5team-front
<<<<<<< HEAD
  newTag: 12db00ba
=======
  newName: readytodev/5team-front
  newTag: 1aaf7e3e
>>>>>>> 5a210c56fcb3b4c2f46fc5b7c21d7a85a8c79f62
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
