apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: readytodev/5team-front
  newName: readytodev/5team-front
  newTag: 12db00ba
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
